-- Hotel ERP Database Creation Script
-- SQL Server 2016+

USE master
GO

-- Drop database if exists
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'HotelMitra')
BEGIN
    ALTER DATABASE HotelMitra SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE HotelMitra
END
GO

-- Create database
CREATE DATABASE HotelMitra
ON PRIMARY
    (NAME = N'HotelMitra', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HotelMitra.mdf', SIZE = 102400KB, MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB)
LOG ON
    (NAME = N'HotelMitra_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HotelMitra_log.ldf', SIZE = 51200KB, MAXSIZE = 2147483648KB, FILEGROWTH = 10240KB)
GO

-- Set database options
ALTER DATABASE HotelMitra SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE HotelMitra SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE HotelMitra SET ANSI_NULLS OFF
GO
ALTER DATABASE HotelMitra SET ANSI_PADDING OFF
GO
ALTER DATABASE HotelMitra SET ANSI_WARNINGS OFF
GO
ALTER DATABASE HotelMitra SET ARITHABORT OFF
GO
ALTER DATABASE HotelMitra SET AUTO_CLOSE OFF
GO
ALTER DATABASE HotelMitra SET AUTO_SHRINK OFF
GO
ALTER DATABASE HotelMitra SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE HotelMitra SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE HotelMitra SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE HotelMitra SET CONCATENATION_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE HotelMitra SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE HotelMitra SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE HotelMitra SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE HotelMitra SET TRUSTWORTHY OFF
GO

PRINT 'HotelMitra database created successfully.'
